WIP

diff --git a/tools/builder/Dockerfile.test b/tools/builder/Dockerfile.test
--- a/tools/builder/Dockerfile.test
+++ b/tools/builder/Dockerfile.test
@@ -64,77 +64,40 @@ WORKDIR ${LIB_CORE_BUILD_DIR}
 
 # Option 1: Compile
 RUN if [ "$DL_LIBCORE" = "ON" ]; then exit 0; fi \
-    && ${LIB_CORE_SRC_DIR}/tools/builder/build.sh --jni --postgres \
+    && ${LIB_CORE_SRC_DIR}/tools/builder/build.sh \
     && mv core/src/libledger-core.so libledger-core.so
+    # cmake_params="\
+    #     # Common flags:
+    #     -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
+    #     -DSYS_OPENSSL=ON \
+    #     -DOPENSSL_SSL_LIBRARIES=/usr/lib/x86_64-linux-gnu \
+    #     -DOPENSSL_INCLUDE_DIR=/usr/include/openssl \
+    #     -DCMAKE_INSTALL_PREFIX=/usr/share/qt5 \
+    #     -DPG_SUPPORT=ON \
+    #     -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql" \
+    #         # Case 1: Release flag
+    #         && if [ "${BUILD_TYPE}" = "Release" ] ; \ 
+    #             then cmake_params="${cmake_params} -DBUILD_TESTS=OFF" \
+    #         # Case 2: Debug flags
+    #         ; elif [ "${BUILD_TYPE}" = "Debug" ] ; \
+    #             then cmake_params="${cmake_params} -DBUILD_TESTS=ON" \              
+    #         # Case 3: Unknown build type
+    #         ; else echo "Error: unknown build type '${BUILD_TYPE}' \
+    #                     (expected: 'Release' or 'Debug' (case sensitive))" \
+    #                && exit 1 \
+    #         ; fi \
+    #         && echo "cmake parameters (${BUILD_TYPE}): ${cmake_params}" \
+    #     && cmake $cmake_params ${LIB_CORE_SRC_DIR} \
+    #     # Avoid "clock skew detected" warning:
+    #     && touch * \
+    #     && make -j$(nproc) \
+    #     && mv core/src/libledger-core.so libledger-core.so \
+    # ; fi
 
-# Option 2: Download
-RUN if [ "${DL_LIBCORE}" = "ON" ]; then \
-        curl -k "${LIBCORE_AWS_BASE_URL}/${LIBCORE_VERSION}/linux/jni/libledger-core_jni.so" \
-             --max-time 600 \
-             --output libledger-core.so \
-    ; fi
 
 # Safeguard to ensure that libledger-core.so exists at this stage
 RUN stat ${LIB_CORE_BUILD_DIR}/libledger-core.so
 
+RUN cp ${LIB_CORE_SRC_DIR}/tools/builder/test.sh test.sh
 
-# Encapsulate compiled library in jar file
-# (generates ledger-lib-core.jar)
-
-FROM debian:stretch AS jar_generator
-
-ARG LIB_CORE_SRC_DIR
-ARG LIB_CORE_BUILD_DIR
-ARG LIB_CORE_JAR_BUILD_DIR
-
-ARG JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
-ARG SBT_DEB=sbt-1.3.10.deb
-
-RUN mkdir -p ${LIB_CORE_BUILD_DIR} ${LIB_CORE_JAR_BUILD_DIR}
-
-RUN apt-get update -qqy \
-    && apt-get install -qqy apt-transport-https curl openjdk-8-jdk \
-    && rm -rf /var/lib/apt/lists/* 
-
-RUN curl -L -o ${SBT_DEB} https://dl.bintray.com/sbt/debian/${SBT_DEB} \
-    && dpkg -i ${SBT_DEB} \
-    && rm ${SBT_DEB}
-
-# Generate interfaces
-WORKDIR ${LIB_CORE_SRC_DIR}
-
-COPY --from=builder ${LIB_CORE_SRC_DIR} .
-
-RUN chmod +x tools/generate_interfaces.sh \
-    && ./tools/generate_interfaces.sh
-
-# Package
-WORKDIR ${LIB_CORE_JAR_BUILD_DIR}
-
-RUN cp -v ${LIB_CORE_SRC_DIR}/api/core/java/* . \
-    && cp -v ${LIB_CORE_SRC_DIR}/api/core/scala/* .
-
-COPY --from=builder ${LIB_CORE_BUILD_DIR}/libledger-core.so \
-                    src/main/resources/resources/djinni_native_libs/libledger-core.so
-
-RUN sbt package
-
-# Move the jar file to build directory and rename it
-RUN find . -name \*.jar -exec mv {} ${LIB_CORE_BUILD_DIR}/ledger-lib-core.jar \;
-
-
-# Make libledger-core.so and ledger-lib-core.jar available 
-# to host or to another Docker image
-
-FROM debian:stretch
-
-ENTRYPOINT [ "cp" , "-rf" , ".", "/build" ]
-
-ARG LIB_CORE_BUILD_DIR
-
-WORKDIR ${LIB_CORE_BUILD_DIR}
-
-COPY --from=builder ${LIB_CORE_BUILD_DIR}/libledger-core.so .
-COPY --from=jar_generator ${LIB_CORE_BUILD_DIR}/ledger-lib-core.jar .
-
-RUN mkdir /build
+ENTRYPOINT [ "./test.sh" ]
